extends: airbnb/base
plugins: [
  import,
]
rules:
  import/no-extraneous-dependencies: [error, { devDependencies: true }]
  # Fix 'chai' expression errors
  no-unused-expressions: 0
  # Fix 'env' require, used with process.env
  no-unused-vars: [error, {varsIgnorePattern: ^env$}]
env:
  es6: true
  node: true
  browser: true
